name: python-unittest

on:
  pull_request:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Lint with pycodestyle
        run: |
          python -m pip install --upgrade pip
          pip install pycodestyle
          pycodestyle --max-line-length=120 --ignore=E402,E501 .
